trigger: 
    branches:
        include:
        - master
    paths:
        include:
        - LibraryCorp/*
        - LibraryCorp.sln
        - scripts/ci-cd/*

pool:
    vmImage: 'ubuntu-latest'

variables:
    buildConfiguration: 'Release'

steps:
- script: dotnet restore
  displayName: 'Restore'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'

- script: 'sudo npm install -g azure-functions-core-tools --unsafe-perm=true --allow-root'

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'CQRS-Azure-Serverless'
    keyVaultName: 'cqrsazureserverless'
    secretsFilter: 'AzureCosmosDBConnection,StorageAccountConnectionString'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration $(buildConfiguration) --output publish_output'
    projects: 'LibraryCorp/LibraryCorp.csproj'
    publishWebProjects: false
    modifyOUtputPath: true
  displayName: 'Publish'

#- task: ArchiveFiles@2
#  displayName: "Zip files"
#  inputs:
#    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
#    includeRootFolder: false
#    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: "$(System.DefaultWorkingDirectory)/publish_output"
    artifactName: 'drop'
  displayName: 'Publish artifact'