trigger: 
    branches:
        include:
        - master
    paths:
        include:
        - LibraryCorp/*
        - LibraryCorp.Tests/*
        - LibraryCorp.sln
        - scripts/ci-cd/*

pool:
    vmImage: 'windows-latest'

variables:
    buildConfiguration: 'Release'
    FunctionHostPath: 'C:\\npm\\prefix\\node_modules\\azure-functions-core-tools\\bin\\func.dll'

steps:
- script: dotnet restore
  displayName: 'Restore'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'

- script: 'npm install -g azure-functions-core-tools --unsafe-perm=true --allow-root'
  displayName: "NPM install azure functions"

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'CQRS-Azure-Serverless'
    keyVaultName: 'cqrsazureserverless'
    secretsFilter: 'AzureCosmosDBConnection,StorageAccountConnectionString'

- script: dotnet test
  workingDirectory: 'LibraryCorp.Tests'
  displayName: 'Integration tests'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration $(buildConfiguration) --output publish_output'
    projects: 'LibraryCorp/LibraryCorp.csproj'
    publishWebProjects: false
    modifyOUtputPath: true
  displayName: 'Publish'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: "$(System.DefaultWorkingDirectory)/publish_output"
    artifactName: 'drop'
  displayName: 'Publish artifact'